### ISSUE TITLE
 libGDX

### ISSUE THREAD

**Issue by houko** [VilenEera/beginner_gdx#1]
有没有兴趣一起做个小游戏，什么主题的都可以。或者完善玛丽奥游戏也可以

**Comment by VilenEera** [comment]
@xiaomoinfo 抱歉才看到留言...我最近比较闲可以的,打算用 libGDX 这个框架么?

**Comment by houko** [comment]
@VilenEera 用egert吧 +netty吧

**Comment by houko** [comment]
qq
83387856
